services:
  - type: web
    name: credit-risk-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python train_on_startup.py && gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
